Repository geosolutions-it/MapStore2-C013, pull requests merged in 2020-10, with the labels that each got.

#43 #18: Maps menu in manage accounts
  assets/themes/default/theme.less
  localConfig.json
Labels: MapStore, Task

#44 #40: Header in the MapView page overlap fix
  assets/themes/default/theme.less
Labels: bug

#46 Navbar position fix for mobile view
  assets/themes/default/theme.less
Labels: bug

#53 Content of some menus #19
  js/menuConfig/menuConfig.json
  js/plugins/ManagerMenu.jsx
  package.json
Labels: Task

#54 Content of some menus #19
  js/menuConfig/menuConfig.js
  js/plugins/ManagerMenu.jsx
  package.json
Labels: Task

#50 Change the color in the title in the home #47
  js/plugins/header/header.less
Labels: Task

#51 Decrease the size of the search bar #48
  assets/themes/default/theme.less
Labels: Task

#52 Display the layers' panel at the bottom of the header #49
  assets/themes/default/theme.less
Labels: Task
